export const SET_USERPHONE_NUMBER = "SET_USERPHONE_NUMBER";
export const SET_USER_CARTITEMS = "SET_USER_CARTITEMS"
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER"
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
